disk_cleaner:
  ordinary:
    garbage:
      - '~/.V2rayU/v2ray-core.log'
      - '~/.python_history'
      - '~/nacos'
      - '~/logs'
      - '~/log'
      - '~/.bytertc'
      - '~/.dubbo'
      - '~/.gnupg'
      - '~/.jprofiler12'
      - '~/.alaya'
      - '~/.UniVPN'
      - '~/.arthas'

  deep:
    garbage:
      - '~/Downloads/*'
      - '~/.bash_history'
      - '~/.zsh_history'
      - '~/.zcompdump*'   # cache file for zsh used to accelerate the command completion feature.
      - '~/kits/leyndell-knight/oss_helper/logs.txt'
      - '~/.cache'

oss_helper:
  oss:
    access_key_id: x
    access_key_secret: x
    endpoint: x
    bucket: x

  log: logs.txt
